### ISSUE TITLE
Reverse not working

### ISSUE THREAD

**Issue by guyzk** [Jaouan/Revealator#2]
When I try to unreveal the view gets clipped but the circular motion back to the first view doesn't happen.
Is it possible to get an unreveal function with a "to" parameter stating the view to be returned to. (Exact opposite of reveal)

**Comment by Jaouan** [comment]
Hi, i've just released the version 1.0.0 with a "to()" function.

**Comment by guyzk** [comment]
Quick response, perfect solution! thanks
