### ISSUE TITLE
Question: Using native implementation if available?

### ISSUE THREAD

**Issue by behelit** [Jaouan/Revealator#6]
Is this library using the native circular reveal implementation on device sdk's that support it? (i.e. 5.0+)
I had a dig through the code but couldn't locate any relevant code.
I'm mainly asking because the performance is not great / smooth on Marshmallow / Nougat devices, in some scenarios

**Comment by behelit** [comment]
Actually, I just noticed that the reveal animation is infinitely smoother if a from view is specified.
Without it, there is a pause delay in the starting animation and it doesn't start from the center.
It is more evident when turning the OS animations up to 5x or 10x

**Comment by Jaouan** [comment]
Hi,

Revealator uses Ozodrukh's circular reveal (https://github.com/ozodrukh/CircularReveal).
Ozodrukh made his circular reveal smart by using native implementation when available.

**Comment by Jaouan** [comment]
Hi,

Thank you for using Revealator ! ;)

Can you open an issue about it. I'll try to fix it soon.

Regards
